### PR TITLE
Recover drawNomNomlDiagram function

### LINKED ISSUE #24: Recover drawNomNomlDiagram function
We should recover the Type Class Hierarchy as it was done in 0.9 arrow version

### PR DESCRIPTION
**Pull request by rachelcarmena**
In order to show **Type Class Hierarchy** sections.

They are missing now. For instance, https://arrow-kt.io/docs/arrow/typeclasses/crosswalk/

Screenshot from 2020-03-03 18-30-39

And the source code for **Type Class Hierarchy**:

```
<h2 id="type-class-hierarchy">Type Class Hierarchy</h2>

<canvas id="hierarchy-diagram"></canvas>
<script>
  drawNomNomlDiagram('hierarchy-diagram', 'diagram.nomnol')
</script>
```

Files recovered from https://github.com/arrow-kt/arrow/pull/1836/files

Closes #24

### CODE REVIEW

**Comment by calvellido** [comment]
Nice catch @rachelcarmena!  I'd like to have a look at it later today if it's ok for you

**Comment by rachelcarmena** [comment]
> Nice catch @rachelcarmena! I'd like to have a look at it later today if it's ok for you

Of course!! I didn't test it, just recovered files :+1: Thank you so much!!!

**Comment by rachelcarmena** [comment]
Thanks for the commit https://github.com/arrow-kt/arrow-site/pull/23/commits/627dd99589273b3c8a13496f44fae0d234f26d64 @AntonioMateoGomez !!! :tada: Now, just to move some directories :+1: Thanks!!

**Comment by rachelcarmena** [comment]
Related PRs:
   * arrow-kt/arrow-core#55
   * arrow-kt/arrow-fx#81
   * https://github.com/arrow-kt/arrow-optics/pull/26
   * https://github.com/arrow-kt/arrow-incubator/pull/57

**Pull request merged**
